### ISSUE TITLE
Error: cannot access local variable 'msg' where it is not associated with a value

### ISSUE THREAD

**Issue by sahilkundu** [vasusen-code/SaveRestrictedContentBot#105]
Failed to save :- https://t.me/GroupName/2**8/2**9

it only download which link is like -------->  https://t.me/c/1**881***0/46
it does not work which link is equal ---------> https://t.me/GroupName/2**8/2**9
![error](https://github.com/vasusen-code/SaveRestrictedContentBot/assets/71582663/48f19d2f-2748-4add-9147-7b4aced949e5)

Please add support.

**Comment by vasusen-code** [comment]
Fixed!
