### ISSUE TITLE
Custom thumbnail Feature doesn't seem to be working

### ISSUE THREAD

**Issue by Shure2005** [vasusen-code/SaveRestrictedContentBot#108]
The bot is able to save the thumbnail but the videos it uploads don't have the custom thumbnail and in fact has no thumbnail at all, it's blank. Any Ideas what might fix it?

**Comment by Shure2005** [comment]
> > The bot is able to save the thumbnail but the videos it uploads don't have the custom thumbnail and in fact has no thumbnail at all, it's blank. Any Ideas what mightthumb_path = await screenshot(file, duration, sender)
> > fix it?
> > thumb_path = await screenshot(file, duration, sender)

??

**Comment by vasusen-code** [comment]
Fixed!
