### ISSUE TITLE
Crashing when deployed to heroku

### ISSUE THREAD

**Issue by BilliBoleMeow** [vasusen-code/SaveRestrictedContentBot#11]
![Screenshot_20220215-160228_Brave](https://user-images.githubusercontent.com/88665437/154044201-57ab107d-b638-480c-9374-dc8e1ea0ccd3.png)

I have tried generating new user session. Still it's the same issue.

**Comment by Selfie-bd** [comment]
> ![Screenshot_20220215-160228_Brave](https://user-images.githubusercontent.com/88665437/154044201-57ab107d-b638-480c-9374-dc8e1ea0ccd3.png)
> 
> I have tried generating new user session. Still it's the same issue.

Try another bot or another telegram user account

**Comment by BilliBoleMeow** [comment]
Why?

**Comment by Selfie-bd** [comment]
> Why?

Maybe problem in spam

**Comment by BilliBoleMeow** [comment]
> > Why?
> 
> Maybe problem in spam

This is permanent account, no spam amrked account. BTw I used telethon user session.

**Comment by DeekshithSH** [comment]
> > > Why?
> > 
> > 
> > Maybe problem in spam
> 
> This is permanent account, no spam marked account. BTw I used telethon user session.

Use Pyrogram String Session

**Comment by DeekshithSH** [comment]
> > > Why?
> > 
> > 
> > Maybe problem in spam
> 
> This is permanent account, no spam marked account. BTw I used telethon user session.

your typed `BOT TOKEN` or `BOT_TOKEN` in Vars

**Comment by BilliBoleMeow** [comment]
![Screenshot_20220215-224409_Brave](https://user-images.githubusercontent.com/88665437/154113825-2b123163-acb9-49d3-b64a-1e66d5ae5b46.png)

With pyrogram session

**Comment by DeekshithSH** [comment]
> 

Send The Var ScreenShot by Hideing Your Values

**Comment by BilliBoleMeow** [comment]
> > 
> 
> Send The Var ScreenShot by Hideing Your Values

![Screenshot_20220215-224831_Brave](https://user-images.githubusercontent.com/88665437/154114603-35e0636c-9961-4dc0-a582-5af785e500cd.png)

**Comment by DeekshithSH** [comment]
Add `AUTH` in Vars Key

**Comment by BilliBoleMeow** [comment]
Thank You & My deepest apologies for this. I checked multiple still missed this. Thank you for all your work.

**Comment by BilliBoleMeow** [comment]
Its working now.

**Comment by Selfie-bd** [comment]
> Its working now.

👍
