### ISSUE TITLE
Cant clone from public channel

### ISSUE THREAD

**Issue by laranganmu** [vasusen-code/SaveRestrictedContentBot#119]
Its show like these. 

An error occurred during cloning of https://t.me/publicchannel/11

Error: invalid literal for int() with base 10: '-100publicchannel'

Any solution ?

Thanks

**Comment by yiyu951** [comment]
have a logic error.
modified as follows 
![image](https://github.com/vasusen-code/SaveRestrictedContentBot/assets/82203049/79ab2023-21bb-4d5d-a8a2-67f875806043)
----->
![image](https://github.com/vasusen-code/SaveRestrictedContentBot/assets/82203049/89a5042a-3b73-4102-b574-d81111667283)

**Comment by laranganmu** [comment]
Thanks its work bro
