### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by perinazzoo** [vasusen-code/SaveRestrictedContentBot#12]
I mean, can I put it running? Do you need help with anything? Lmk

**Comment by vasusen-code** [comment]
Yeah it's running fine, ig all known bugs are fixed.

**Comment by perinazzoo** [comment]
Can I run it as a user instead of a bot?

**Comment by vasusen-code** [comment]
You can if you use Bot as USERBOT and replace incoming=True to outgoing=True.

But it would be a mess, using it through bot also keeps your acc safe.
