### ISSUE TITLE
Error: invalid literal for int() with base 10: '-100SRCBtest'

### ISSUE THREAD

**Issue by QAQOAOQAO030** [vasusen-code/SaveRestrictedContentBot#145]
![image](https://github.com/vasusen-code/SaveRestrictedContentBot/assets/148039348/6a765bf5-a86b-4d2a-ba0a-a37036545117)

It seems that bot cannot deal with this type of link.
Any good method?

**Comment by sniffex** [comment]
Hey I faced this issues too, May I know how do you resolves it?

**Comment by LegendarySSS** [comment]
I have the same problem, how did you solve it
