### ISSUE TITLE
Error: Can't upload files bigger than 2000 MiB

### ISSUE THREAD

**Issue by QAQOAOQAO030** [vasusen-code/SaveRestrictedContentBot#153]
Is there a variable that can be modified?
or there's no way to fix this?

**Comment by timgahmen** [comment]
> Is there a variable that can be modified? or there's no way to fix this?

files bigger than 2000 MiB you need telegram premium ...

if you have, login in the SCRB (userbot) ... then it should work. I can not test it, I not having Telegram premium 😉
