### ISSUE TITLE
Unable to save video files

### ISSUE THREAD

**Issue by Harshit-Shrivastav** [vasusen-code/SaveRestrictedContentBot#22]
![IMG_20220529_102033_493](https://user-images.githubusercontent.com/87630299/170852800-5e4ca29e-ada9-4993-b38a-ac08d7c6a673.jpg)

Whenever i am trying to save video files i am facing the problem (attached screenshot)
But after adding thumbnail video file is successfully saving
Please solve the problem so that i can save video files without thumbnail

**Comment by asmibls631** [comment]
How to add thumbnails bro

**Comment by asmibls631** [comment]
Finally, the problem was solved...
