### ISSUE TITLE
Error Private and Stay online

### ISSUE THREAD

**Issue by Prontera23** [vasusen-code/SaveRestrictedContentBot#54]
BOT cant online a few moment later and cant save file from private channel after downloading.

Failed to save: https://t.me/c/1869004839/5

**Comment by Prontera23** [comment]
Deploy on koyeb bro

**Comment by kopianb** [comment]
On koyeb i was deploy with github connected.
When i trying with docker the telegram session cant connect.

**Comment by Prontera23** [comment]
Just connect and deploy using github. And add all variable there.
Port using 80
