### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by itzharshit** [vasusen-code/SaveRestrictedContentBot#72]
Ethon library error cannot import video_metadata

Please fix it

**Comment by Seeger0216** [comment]
That's my similar problem :
`````
ERROR: Could not find a version that satisfies the requirement ethon==1.3.8
ERROR: No matching distribution found for ethon==1.3.8
WARNING: You are using pip version 21.0.1; however, version 23.0 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
ERROR: Service 'app' failed to build: The command '/bin/sh -c pip3 install --no-cache-dir -r requirements.txt' returned a non-zero code: 1
`````

**Comment by itzharshit** [comment]
> That's my similar problem :
> 
> ```
> ERROR: Could not find a version that satisfies the requirement ethon==1.3.8
> ERROR: No matching distribution found for ethon==1.3.8
> WARNING: You are using pip version 21.0.1; however, version 23.0 is available.
> You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
> ERROR: Service 'app' failed to build: The command '/bin/sh -c pip3 install --no-cache-dir -r requirements.txt' returned a non-zero code: 1
> ```

I guess, owner of ethon (vasusen-code) have removed the ethon dependency or this library is no more available for use.
Find some alternative and replace yourself the dependency
