### ISSUE TITLE
error when try to deploy it on vps (

### ISSUE THREAD

**Issue by sabnam777** [vasusen-code/SaveRestrictedContentBot#77]
ERROR: Could not find a version that satisfies the requirement ethon==1.3.8
ERROR: No matching distribution found for ethon==1.3.8
WARNING: You are using pip version 21.0.1; however, version 23.0.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
then i edited the requirements from ethon==1.3.8 to ethon==69.2
then i encountered a new error 
and it says 
Successfully built cdbb418df3db
Successfully tagged save_app:latest
Creating srcbot ... done
Attaching to srcbot
srcbot | starting Bot ~@DroneBots
srcbot | Traceback (most recent call last):
srcbot |   File "/usr/local/lib/python3.9/runpy.py", line 188, in _run_module_as_main
srcbot |     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
srcbot |   File "/usr/local/lib/python3.9/runpy.py", line 147, in _get_module_details
srcbot |     return _get_module_details(pkg_main_name, error)
srcbot |   File "/usr/local/lib/python3.9/runpy.py", line 111, in _get_module_details
srcbot |     __import__(pkg_name)
srcbot |   File "/app/main/__init__.py", line 5, in <module>
srcbot |     from telethon.sessions import StringSession
srcbot |   File "/usr/local/lib/python3.9/site-packages/telethon/__init__.py", line 4, in <module>
srcbot |     from ._misc import utils as _  # depends on helpers and _tl
srcbot |   File "/usr/local/lib/python3.9/site-packages/telethon/_misc/utils.py", line 23, in <module>
srcbot |     from . import markdown, html
srcbot |   File "/usr/local/lib/python3.9/site-packages/telethon/_misc/markdown.py", line 8, in <module>
srcbot |     import markdown_it
srcbot | ModuleNotFoundError: No module named 'markdown_it'
srcbot exited with code 1

**Comment by vasusen-code** [comment]
fixed
