### ISSUE TITLE
ERROR: Add in ForceSub channel, or check your channel id.

### ISSUE THREAD

**Issue by catbonny** [vasusen-code/SaveRestrictedContentBot#81]
when i send invite link of private channel it give me ERROR: Add in ForceSub channel, or check your channel id.
what should i do ? i check my variables and everything good

**Comment by catbonny** [comment]
actually i try to send any link of public or private channel same msg everytime ?
ERROR: Add in ForceSub channel, or check your channel id.

**Comment by 1836669** [comment]
Please put the bot in your channel settings admin, it can be solved

**Comment by THE-DSR** [comment]
> actually i try to send any link of public or private channel same msg everytime ? ERROR: Add in ForceSub channel, or check your channel id.

Make bot admin in your force_sub channel
