### ISSUE TITLE
bash: gunicorn: command not found

### ISSUE THREAD

**Issue by neomnitrix** [vasusen-code/SaveRestrictedContentBot#83]
when i deploy this on render after build it shows ''bash: gunicorn: command not found''

**Comment by digimaxme** [comment]
> Batch command not working

did you find the solution. Mine Also not working

**Comment by neomnitrix** [comment]
> > Batch command not working
> 
> did you find the solution. Mine Also not working

No, i talk to devloper he said use old fork then blocked me when i using old forks its not working coming enthon error issue 🥲
