### ISSUE TITLE
I can't download videos from private channel, but there are no problems with pictures

### ISSUE THREAD

**Issue by passberypy** [vasusen-code/SaveRestrictedContentBot#85]
I can't download videos from private channel, but there are no problems with pictures. With public channels no such problem, I can download both video and photos, but with private only photos, what is the problem?

![image](https://user-images.githubusercontent.com/89548806/227733342-7f54d9b3-c2a8-43b7-9c70-7784f3db8814.png)

**Comment by passberypy** [comment]
> > I can't download videos from private channel, but there are no problems with pictures. With public channels no such problem, I can download both video and photos, but with private only photos, what is the problem?
> > ![image](https://user-images.githubusercontent.com/89548806/227733342-7f54d9b3-c2a8-43b7-9c70-7784f3db8814.png)
> 
> Where is ur bot hosted??

VPS

**Comment by passberypy** [comment]
> > > > I can't download videos from private channel, but there are no problems with pictures. With public channels no such problem, I can download both video and photos, but with private only photos, what is the problem?
> > > > ![image](https://user-images.githubusercontent.com/89548806/227733342-7f54d9b3-c2a8-43b7-9c70-7784f3db8814.png)
> > > 
> > > 
> > > Where is ur bot hosted??
> > 
> > 
> > VPS
> 
> Install ffmpeg there ......

Thank you, but i have ffmpeg

**Comment by sdfdsgdsfdsfdfdgds** [comment]
I was able to dowload the video but bot able to upload the video

**Comment by vasusen-code** [comment]
Fixed
