### ISSUE TITLE
Bot failed to upload the video to telegram.

### ISSUE THREAD

**Issue by sdfdsgdsfdsfdfdgds** [vasusen-code/SaveRestrictedContentBot#87]
After deploying the bot, bot was able to extract the msg form public channel, but was not able to upload to the bot, say Failed to save

**Comment by digimaxme** [comment]
same problem occurs with me. can anybody help?

**Comment by Harshith67** [comment]
Same Problem bro Bot Failed to upload

**Comment by rohitsir1999** [comment]
> same problem occurs with me. can anybody help?

Yes i can i have the fixed repo

**Comment by sdfdsgdsfdsfdfdgds** [comment]
> > same problem occurs with me. can anybody help?
> 
> Yes i can i have the fixed repo

what is the fix, do you have corrected code

**Comment by craigliu** [comment]
This is because the video_metadata function in pyroplug.py returns None. On line 112, when trying to access data["duration"], it results in a 'NoneType' object not being subscriptable error. Setting the duration to a fixed value, for example 20, can solve the problem.

**Comment by vasusen-code** [comment]
Fixed
