### ISSUE TITLE
batch command not working

### ISSUE THREAD

**Issue by mlbtvps** [vasusen-code/SaveRestrictedContentBot#92]
![16849236001375309572182499730581](https://github.com/vasusen-code/SaveRestrictedContentBot/assets/119069067/b70401c0-5551-472f-ba4d-ea42ad43cfc8)
![Screenshot_20230524_165149_Vivaldi Browser](https://github.com/vasusen-code/SaveRestrictedContentBot/assets/119069067/665ae474-f0cc-4499-a62a-112ec3b4f9e6)

**Comment by vasusen-code** [comment]
Batch related issues are fixed i guess, if you are still facing you may open a new issue
